### ISSUE TITLE
Git Issue

### ISSUE THREAD

**Issue by MichaelGregg** [cisc3620/2-draw-triangle#11]
@rivlev in the terminal i did 
git checkout -b hw
then 
git checkout master
then
git reset --hard 84d978b
like you told me to do,
and then i go to my private repository to create a pull request but it still says theres nothing to compare.  Did i do what you told me to do wrong? There are several apostrophes in your message telling me what to do, im not sure if those are variables or if i should include the apostrophes in the terminal commands, or if i should ignore them.  Additionally, before you tell me to do the "git checkout master" command, you say "Then go back to master".  I am not sure what you mean by then go back to master, do you mean change directories in the terminal to master?

**Comment by rivlev** [comment]
the apostrophes are formatting for github, ignore them
git checkout master is what "goes back to master"
When I look at your private repository there is no hw branch and master has not been reset. Please make sure you applied those changes to the right repository.

**Comment by MichaelGregg** [comment]
@rivlev By those changes are you referring to what these commands 
git checkout -b hw
git checkout master
git reset --hard 84d978b
should have done?  How do i make sure i have applied the changes to the right repository?

**Comment by MichaelGregg** [comment]
@rivlev ...Also, should starting over from scratch and following the directions correctly fix the problem and submit the completed assignment, or is something off that would disallow this? Because i have started over several times from scratch following the directions correctly, but get the same errors.  To not be able to start over is very frustrating

**Comment by rivlev** [comment]
"Starting over" is not possible from the github classroom repository that was created for you.

You can create your own repository and clone the 2-draw-triangle repository and start from there, making sure to first create a hw branch as it says in the instructions.

**Comment by MichaelGregg** [comment]
@rivlev What do you think is my best course of action at this point?

**Comment by rivlev** [comment]
Work in the repository you already have.
Navigate to 2-draw-house-MichaelGregg 
do
git checkout -b hw
git checkout master
git reset --hard 84d978b

Go into github online and make sure you see the two branches. hw should look the way master looks now, master should not have any of your commits.

**Comment by MichaelGregg** [comment]
@rivlev After navigating to 2-draw-house-MichaelGregg i did 
git checkout -b hw
the response was
fatal: A branch named 'hw' already exists.

**Comment by MichaelGregg** [comment]
@rivlev Should i try the next step? that would be: git checkout master

**Comment by rivlev** [comment]
You need to push the hw branch.

git checkout hw

make some trivial change -- e.g. add a readme
add, commit

git push origin hw

**Comment by MichaelGregg** [comment]
@rivlev I did git checkout hw
the response:
error: Your local changes to the following files would be overwritten by checkout:
	Glitter/Sources/main.cpp
Please commit your changes or stash them before you switch branches.
Aborting
I changed the file and saved it, then did the add and commit steps to get this response from github:
![screen shot 2017-02-14 at 6 31 54 pm](https://cloud.githubusercontent.com/assets/25493211/22961014/bf72ca9e-f310-11e6-8e4e-25b29bb1d931.png)

**Comment by rivlev** [comment]
You are comparing master and master. Compare master and hw

**Comment by MichaelGregg** [comment]
@rivlev I did git checkout hw
the response:
error: Your local changes to the following files would be overwritten by checkout:
Glitter/Sources/main.cpp
Please commit your changes or stash them before you switch branches.
Aborting
I changed the file and saved it, then did the add and commit steps to get this response from github:
Previous message i used wrong screenshot:
![screen shot 2017-02-14 at 11 52 43 pm](https://cloud.githubusercontent.com/assets/25493211/22961057/15a6cc3a-f311-11e6-8816-b039fb35c17d.png)

**Comment by MichaelGregg** [comment]
@rivlev I changed the numerical values in my vertices so it was a large change so i do not understand why it still thinks they are identical

**Comment by rivlev** [comment]
There should be no changes to main.cpp in the master branch since git reset should roll it back to my last commit.
It looks like you made changes and then checked out hw instead of vice versa.

Go back to the master branch: git checkout master
Revert it again: git reset --hard 84d978b
Apply to the remote repository: git push -f origin master

Go back to hw: git checkout hw
Push branch to remote: git push origin hw

Go to github
Create pull request from hw to master

**Comment by MichaelGregg** [comment]
git checkout master:
![screen shot 2017-02-15 at 12 10 44 am](https://cloud.githubusercontent.com/assets/25493211/22961352/494a2dc8-f313-11e6-9949-78bcb9a7648d.png)
Then i tried the reset and push commands:
![screen shot 2017-02-15 at 12 12 26 am](https://cloud.githubusercontent.com/assets/25493211/22961382/834b075e-f313-11e6-86d6-f95ab2f3c6cf.png)
Then i tried git checkout and git push origin hw:
![screen shot 2017-02-15 at 12 13 21 am](https://cloud.githubusercontent.com/assets/25493211/22961399/a591d676-f313-11e6-8a39-f5a551076ada.png)

**Comment by rivlev** [comment]
Looking at your online repository -- it now looks good, you should be able to create the pull request.

**Comment by MichaelGregg** [comment]
I think i created the pull request not sure if it worked it said there were conflicts that needed to be resolved

**Comment by MichaelGregg** [comment]
I clicked resolve conflicts and it took me to a text editor and then i clicked back which i apparently should not have done because now i can not navigate back to see if it worked.  I did fill out my name and what i drew and clicked submit though

**Comment by MichaelGregg** [comment]
This shows up after i create the pull request:
![screen shot 2017-02-15 at 12 44 52 am](https://cloud.githubusercontent.com/assets/25493211/22962004/1c21dd1e-f318-11e6-95e3-afddffe963ef.png)
and this shows up when i click resolve conflicts:
![screen shot 2017-02-15 at 12 47 58 am](https://cloud.githubusercontent.com/assets/25493211/22962051/76736cce-f318-11e6-8cee-ea3c41e297ad.png)

**Comment by rivlev** [comment]
You don't need to resolve conflicts, this is fine
