### ISSUE TITLE
"Access Denied" in VS

### ISSUE THREAD

**Issue by SIRGHST** [cisc3620/2-draw-triangle#3]
Whenever I try to run my main.cpp I get an "Access Denied" message.Does anyone know how to stop this from happening? Ive attached the exact message
![screenshot 1](https://cloud.githubusercontent.com/assets/7463854/22899077/90639f5e-f1f7-11e6-95f8-dae914ae3a45.png)

@rivlev

**Comment by TarekCodes** [comment]
Right click "Glitter" in the Solution Explorer on the right and set it as startup project, this should fix it.

**Comment by SIRGHST** [comment]
thank you! it worked

**Comment by rivlev** [comment]
Closing
