### ISSUE TITLE
What to do

### ISSUE THREAD

**Issue by MichaelGregg** [cisc3620/2-draw-triangle#4]
@rivlev Can i have some advice or hints as to how to alter the code in order to produce a house instead of a triangle? I have repeatedly been reviewing the material that you emailed us since thursday but can not derive from it the best way to edit main.cpp in order to achieve the objective.  What do i need to do?

**Comment by rivlev** [comment]
Think of an image you can make of three or more triangles. Draw the image on graph paper and write down the coordinates of each vertex of each triangle (make sure they are all between 0 and 1). Change the vertices array to hold the vertices of your triangle instead of the triangle that is there.

**Comment by MichaelGregg** [comment]
Thank you,
This code: ![screen shot 2017-02-13 at 5 21 55 pm](https://cloud.githubusercontent.com/assets/25493211/22906096/07a0df82-f211-11e6-89f0-73a5476a0442.png)
Outputs only first two triangles:
![screen shot 2017-02-13 at 5 19 52 pm](https://cloud.githubusercontent.com/assets/25493211/22906030/adfd70da-f210-11e6-8373-5623077f8563.png)
But if i comment out the first triangle:
![screen shot 2017-02-13 at 5 20 44 pm](https://cloud.githubusercontent.com/assets/25493211/22906052/cb972a32-f210-11e6-990e-f2529c744332.png)
The output is the second two?
![screen shot 2017-02-13 at 5 22 19 pm](https://cloud.githubusercontent.com/assets/25493211/22906099/0cb81288-f211-11e6-9fe6-b0b014abcf2d.png)
Is there a reason only two of the triangles show up?

**Comment by MichaelGregg** [comment]
Thank you, 
This code: 
![screen shot 2017-02-13 at 5 19 52 pm](https://cloud.githubusercontent.com/assets/25493211/22906178/69412170-f211-11e6-8976-82dcc94d06cd.png)
Outputs the first two triangles:
![screen shot 2017-02-13 at 5 20 44 pm](https://cloud.githubusercontent.com/assets/25493211/22906192/7748fc84-f211-11e6-8ab4-55d8fd9f7138.png)
But if i comment the first triangle out:
![screen shot 2017-02-13 at 5 21 55 pm](https://cloud.githubusercontent.com/assets/25493211/22906196/7eb18a18-f211-11e6-8b33-73b6c007c617.png)
I get the second two:
![screen shot 2017-02-13 at 5 22 19 pm](https://cloud.githubusercontent.com/assets/25493211/22906211/8e2c85d8-f211-11e6-89b2-ad2e75b67699.png)
Is there a reason all three triangles will not simultaneously show up?

**Comment by Natia94** [comment]
you should use GLuint indices[] = { } which triangle is first, second, third.... @MichaelGregg

**Comment by Natia94** [comment]
you should write C coordinates once you are overlapping them, This  is from the tutorial: https://www.learnopengl.com/#!Getting-started/Hello-Triangle  @MichaelGregg 
![screen shot 2017-02-13 at 6 15 46 pm](https://cloud.githubusercontent.com/assets/22197300/22907721/9a06e694-f218-11e6-81a2-9682a8098446.png)

**Comment by MichaelGregg** [comment]
Thank you, I understand that using indexed drawing will help but am having trouble applying it to my code.  I understand GLfloat vertices[] in that it is specifying the four vertices, and i understand how in my case the Top Right, Bottom Right, Bottom Left, and Top Left would be A,E,D,C respectively. But when i alter my code in that way:
![screen shot 2017-02-13 at 7 38 32 pm](https://cloud.githubusercontent.com/assets/25493211/22909775/15554038-f224-11e6-83b8-2c0cade0d33e.png)
The output it the third triangle only:
![screen shot 2017-02-13 at 7 40 32 pm](https://cloud.githubusercontent.com/assets/25493211/22909831/5ce0a3b6-f224-11e6-8c21-5b8c4267bc3f.png)

**Comment by destroyer3b** [comment]
@MichaelGregg 
Change this line:
` glDrawArrays(GL_TRIANGLES, 0, 6);`

Change the 6 to the # of vertices you have

**Comment by rivlev** [comment]
That should fix it.

Please close this issue if your problem is solved.

**Comment by MichaelGregg** [comment]
Thanks, when i change the 6 to 4 i get the same output. Would 4 (a,b,c,d) be the number of vertices or am i confused?

**Comment by rivlev** [comment]
the number of vertices is 9

3 per triangle

**Comment by MichaelGregg** [comment]
I get only the third triangle again when i change it to 9.  I think it is a problem with GLfloat vertices[] because as pictured above the top triangle of the house is commented out so i dont think the top of the house is being constructed

**Comment by rivlev** [comment]
Does it work when you uncomment it

**Comment by MichaelGregg** [comment]
I get this as output:
![screen shot 2017-02-13 at 9 27 33 pm](https://cloud.githubusercontent.com/assets/25493211/22912458/707809be-f233-11e6-8831-27985442f452.png)
When i edit GLfloat vertices[] where it was in the original program, adding GLuint indices[] directly underneath it:
![screen shot 2017-02-13 at 9 31 58 pm](https://cloud.githubusercontent.com/assets/25493211/22912522/e056d45e-f233-11e6-8599-246da4d247e6.png)
and i changed  glDrawArrays to glDrawArrays(GL_TRIANGLES, 0, 9);   // draw the objects

**Comment by rivlev** [comment]
You are still missing one triangle in your indices array

**Comment by MichaelGregg** [comment]
So i need something like this?
![screen shot 2017-02-13 at 10 51 19 pm](https://cloud.githubusercontent.com/assets/25493211/22914591/53abd174-f23f-11e6-8082-09a18fd6d8f7.png)
How should i find out what values go into that command? that section of the tutorial is focusing on rectangles

**Comment by rivlev** [comment]
It doesn't look like you are using that second indices array. Forget about it and go back to your vertices array. The first time you posted it looked good and should have worked with the edit to the glDrawArrays command. In the most recent time you posted two vertices had been deleted.

**Comment by MichaelGregg** [comment]
Thanks youre right
