### ISSUE TITLE
problem with Indices [ ]

### ISSUE THREAD

**Issue by Natia94** [cisc3620/2-draw-triangle#5]
![screen shot 2017-02-13 at 11 05 37 pm](https://cloud.githubusercontent.com/assets/22197300/22914896/58e33d88-f241-11e6-8a82-41133ce70457.png)
![screen shot 2017-02-13 at 11 06 17 pm](https://cloud.githubusercontent.com/assets/22197300/22914900/5a85c7c8-f241-11e6-91f4-c8146c943d95.png)

@rivlev Professor I have first and the fourth triangle and for some reason I can not see the second and the third one. I think I have problem with Vertices array, how can I solve this issue? Thanks!

**Comment by rivlev** [comment]
Did you modify your code to use an element buffer? You would get this if it was just drawing the vertices data directly, reading ABC as one triangle and DEF as another.
