### ISSUE TITLE
Git Issue

### ISSUE THREAD

**Issue by MichaelGregg** [cisc3620/2-draw-triangle#8]
I figured out what i am doing wrong, and have gotten this to output from fixing the errors:
Screen Shot 2017-02-14 at 1.21.36 PM.png
(@rivlev removed -- please do not post full code)

But git is not working.  When i try to add main.cpp from the 2-draw-triangle level of the directory i get this:

fatal: pathspec 'main.cpp' did not match any files

But if i navigate to Sources, the directory in which main is, when i do git add main.cpp i get no message in response, so then i do git commit, which gives me this:

On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
Untracked files:
	../../.DS_Store
	../.DS_Store

nothing added to commit but untracked files present

I dont think that is what should come back as a response.  I then try git push origin hw which gives me this:

error: src refspec hw does not match any.
error: failed to push some refs to 'https://github.com/cisc3620/2-draw-triangle.git'

I have the assignment completed correctly, what do i need to do in order to properly submit it?

**Comment by MichaelGregg** [comment]
I have tried several times starting over from the beginning following the exact instructions but something is clearly wrong because it will no work. i now get this message when i try the commit command:

J3611-B1-49330:2-draw-triangle mgzelasko$ git commit -m "message"
On branch master
Your branch is ahead of 'origin/master' by 2 commits.
(use "git push" to publish your local commits)
Untracked files:
.DS_Store
Glitter/.DS_Store

nothing added to commit but untracked files present
J3611-B1-49330:2-draw-triangle mgzelasko$ git push origin hw
error: src refspec hw does not match any.
error: failed to push some refs to 'https://github.com/cisc3620/2-draw-triangle.git'

**Comment by destroyer3b** [comment]
@MichaelGregg there is no origin hw branch for this repo.
git push
is all you need

get to the directory where main.cpp is and do:
git add main.cpp
git commit -m "message"
git push

**Comment by MichaelGregg** [comment]
Thank you, I started the process all over again from the beginning before i saw this message.  In order for it work, i need to execute git push in between which two steps in the Github Submission Instructions?

**Comment by MichaelGregg** [comment]
After modifying the files, but before the Stage Your Files step perhaps?

**Comment by destroyer3b** [comment]
@MichaelGregg 
git push is the last step , the order is the same , just that theres no need for git push 'origin hw'

**Comment by MichaelGregg** [comment]
When i follow the steps but use the command git push leaving out 'origin hw' i get this:

Michael-Zelaskos-MacBook-Pro:Sources mgzelasko$ git push
remote: Permission to cisc3620/2-draw-triangle.git denied to MichaelGregg.
fatal: unable to access 'https://github.com/cisc3620/2-draw-triangle.git/': The requested URL returned error: 403

**Comment by MichaelGregg** [comment]
@destroyer3b @rivlev what is the problem how do i fix this

**Comment by destroyer3b** [comment]
@MichaelGregg I am guessing you are not cloning from the https link from your repo. the link should be like https://github.com/destroyer3b/2-draw-house-destroyer3b.git with your username. Try starting over and fork this lab and clone using the link with your username.

**Comment by MichaelGregg** [comment]
Thanks, When i start over if i clone from the right repository, do i follow the instructions exactly, or should i do git push leaving out 'origin hw'?

**Comment by MichaelGregg** [comment]
@destroyer3b Thanks, When i start over if i clone from the right repository, do i follow the instructions exactly, or should i do git push leaving out 'origin hw'?

**Comment by destroyer3b** [comment]
@MichaelGregg follow the instructions and just git push

**Comment by MichaelGregg** [comment]
@destroyer3b  When i follow the instructions and do just git push:

Michael-Zelaskos-MacBook-Pro:Sources mgzelasko$ git push
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 35.97 KiB | 0 bytes/s, done.
Total 6 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/cisc3620/2-draw-house-MichaelGregg.git
   84d978b..e71d64c  master -> master

I then try to move to the next step but 'hw' is not in 'compare'.  It says "There isnt anything to compare"

**Comment by destroyer3b** [comment]
@MichaelGregg you compare cisc3620 master with your own master

**Comment by MichaelGregg** [comment]
@destroyer3b The only option to choose for what to set master to is 'master' there is no cisc3620 option to set master to

**Comment by MichaelGregg** [comment]
@destroyer3b  If i hit compare across forks, there is only one option for both the base fork and head fork which is CISC3620/2-Draw-House-MichaelGregg

**Comment by destroyer3b** [comment]
@MichaelGregg did you do new pull request from within your repo? should look like this
![git](https://cloud.githubusercontent.com/assets/24684787/22954134/c4b52034-f2e2-11e6-9edb-733c5a5b8b8a.jpg)

**Comment by MichaelGregg** [comment]
@destroyer3b I clicked 2-draw-house-MichaelGregg private and hit new pull request from there and i get this 
![screen shot 2017-02-14 at 6 31 54 pm](https://cloud.githubusercontent.com/assets/25493211/22954344/ea2a1d6e-f2e3-11e6-85be-f808d8ea776c.png)

then if i hit compare across forks:
![screen shot 2017-02-14 at 6 32 34 pm](https://cloud.githubusercontent.com/assets/25493211/22954361/ff24066c-f2e3-11e6-9b35-25b433a9f2ec.png)

**Comment by MichaelGregg** [comment]
@destroyer3b  My latest commit does show up:
![screen shot 2017-02-14 at 6 34 20 pm](https://cloud.githubusercontent.com/assets/25493211/22954461/918bdd36-f2e4-11e6-8a00-0f175c5541bb.png)

**Comment by destroyer3b** [comment]
@MichaelGregg That means nothing changed between the original and yours. Did you edit the main.cpp file again after you clone? It overwrites to the original again.

**Comment by MichaelGregg** [comment]
@destroyer3b Yes i did edit main.cpp after i cloned it from my private repository i changed main to output correctly

**Comment by destroyer3b** [comment]
@MichaelGregg and you git add , commit, push ? If you did then there should be your latest commit showing

you should be comparing cisc3620/2-draw-house-username with username/2-draw-house-username, like in the picture from before.

**Comment by MichaelGregg** [comment]
@destroyer3b yes i followed the steps cloned it, modified it, then staged

**Comment by MichaelGregg** [comment]
@destroyer3b Should i be able to start from the beginning creating a new directory and do it again starting from the beginning and follow the steps exactly? or is something corrupted that needs to be fixed before i can do that?

**Comment by rivlev** [comment]
See https://github.com/cisc3620/docs/issues/6
