### ISSUE TITLE
.PNG broken when trying to preview on GitHub

### ISSUE THREAD

**Issue by ghost** [cisc3620/2-draw-triangle#9]
Instructions are "execute the program, save the image that's created (using a screenshot tool), and move the image into the top level of your repository." However after committed the .png file and trying to preview it on GitHub, it's a broken file. Is there a fix or do you want another file type?

**Comment by rivlev** [comment]
png's should work, I have been able to view others. Please make sure it is a good file that you can view on your computer. I was also not able to see anything when I downloaded it from github.

**Comment by ghost** [comment]
I used the snipping tool and Print Screen + copy paste to paint. It works fine on my computer. Once I upload it onto GitHub, the image is corrupted.

**Comment by ghost** [comment]
Image is now fixed.
